[tox]
minversion = 1.8
envlist = py39-ansible
skipsdist = true

[testenv]
passenv = *
deps =
    -r tox-requirements.txt
    ansible
    molecule
    molecule-docker
commands =
    molecule --version
    molecule test --destroy always
