---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: ubuntu
    image: ubuntu:latest
    pre_build_image: true
  - name: ubuntu2204
    image: ubuntu:22.04
    pre_build_image: true
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
