---
- name: Start Vector service
  become: true
  ansible.builtin.service:
    name: vector
    state: restarted
- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
